#!/bin/bash

echo
echo USER -- PROCS -- TIME -- JOB
echo "-----------------------------------------"

while read line; do

USER_TIME=`echo $line | awk '{print$4 " -- " $2 " -- " $3 " minutes -- " }'`
NAME=`echo $line | awk '{print$1}' | awk -F'_' '{print$3}'`

echo $USER_TIME $NAME

done < /opt/BioBatch/Jobs/Main.queue

echo "-----------------------------------------"
echo "`cat /opt/BioBatch/Jobs/.procs_in_use` of $BIOBATCH_MAX_PROCS processors in use"
echo
